channels:
- conda-forge
- pytorch
dependencies:
# Jupyter
- jupyterlab=2
# Python Kernel
- matplotlib=3.1
- numpy=1.17
- scipy=1.4
- pip
- fenics
- h5py
- pytorch
- torchvision
- torchaudio
- cudatoolkit=10.2
